/**
 * Managed-runtime deadline hierarchy. Each outer boundary must outlive the
 * inner operation it awaits, with enough margin to persist observations and
 * return the enclosing acknowledgement.
 */
export const PROVIDER_ACCEPT_TIMEOUT_MS = 60_000;
const RUNTIME_ENVELOPE_MARGIN_MS = 15_000;
export const AGENT_HOST_CONTROL_TIMEOUT_MS =
  PROVIDER_ACCEPT_TIMEOUT_MS + RUNTIME_ENVELOPE_MARGIN_MS;
export const AGENT_HOST_READY_TIMEOUT_MS = AGENT_HOST_CONTROL_TIMEOUT_MS;
export const AGENT_HOST_LAUNCH_TICKET_TTL_MS = AGENT_HOST_READY_TIMEOUT_MS;
export const LIFECYCLE_REQUEST_TIMEOUT_MS =
  AGENT_HOST_CONTROL_TIMEOUT_MS + RUNTIME_ENVELOPE_MARGIN_MS;
export const CONTROLLER_SHUTDOWN_TIMEOUT_MS =
  LIFECYCLE_REQUEST_TIMEOUT_MS + RUNTIME_ENVELOPE_MARGIN_MS;
export const RELEASE_HANDOVER_OLD_OWNER_GRACE_MS =
  CONTROLLER_SHUTDOWN_TIMEOUT_MS + RUNTIME_ENVELOPE_MARGIN_MS;
export const RELEASE_HANDOVER_PROMOTION_TIMEOUT_MS =
  RELEASE_HANDOVER_OLD_OWNER_GRACE_MS + RUNTIME_ENVELOPE_MARGIN_MS;
