import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// Regenerate src/web/assets/fontData.ts from the woff2 binaries in
// src/web/assets/fonts. Fonts are embedded as base64 so the TypeScript build
// emits only .js files and the runtime package needs no binary font assets.
const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const fontDir = join(root, "src/web/assets/fonts");
const output = join(root, "src/web/assets/fontData.ts");

const files = readdirSync(fontDir)
  .filter((name) => name.endsWith(".woff2"))
  .sort();

if (files.length === 0) {
  throw new Error(`No woff2 files found in ${fontDir}`);
}

const lines = [
  "// Generated by scripts/embed-fonts.mjs. Do not edit by hand.",
  "// Self-hosted Inter + JetBrains Mono (latin subset) embedded as base64 so the",
  "// compiled dist ships only .js files and the web server needs no binary asset",
  "// files at runtime. Regenerate after replacing any woff2 in web/assets/fonts.",
  "export const FONT_WOFF2_BASE64: Readonly<Record<string, string>> = Object.freeze({"
];
for (const file of files) {
  const key = file.replace(/\.woff2$/u, "");
  const base64 = readFileSync(join(fontDir, file)).toString("base64");
  lines.push(`  "${key}": "${base64}",`);
}
lines.push("});", "");

writeFileSync(output, lines.join("\n"));
console.log(`Embedded ${files.length} fonts into ${output}`);
